// The public barrel is generated, sorted, and complete.
//
// Every module used to append its export to the end of src/index.ts, so four
// parallel streams appended to the same line and every sibling pair conflicted
// on merge. Sorted order makes two new modules land at different lines, so the
// collision stops by construction rather than by review attention. Completeness
// makes a module that is built but unreachable a build failure rather than a
// discovery months later.
//
// Run with --write to regenerate. Run with no arguments to verify.
import { readdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const srcDir = fileURLToPath(new URL("../src/", import.meta.url));
const barrelPath = `${srcDir}index.ts`;

// Modules deliberately absent from the public surface.
const internal = new Set(["index.ts"]);

const header = [
  "// Generated by scripts/check-barrel.mjs. Sorted so parallel modules do not",
  "// collide on the same line. Run `node scripts/check-barrel.mjs --write` after",
  "// adding a module.",
];

const entries = await readdir(srcDir, { withFileTypes: true });
const modules = entries
  .filter((entry) => entry.isFile() && entry.name.endsWith(".ts") && !entry.name.endsWith(".d.ts"))
  .map((entry) => entry.name)
  .filter((name) => !internal.has(name))
  .sort();

const expected = `${[...header, ...modules.map((name) => `export * from "./${name.replace(/\.ts$/, ".js")}";`)].join("\n")}\n`;

if (process.argv.includes("--write")) {
  await writeFile(barrelPath, expected, "utf8");
  console.log(`barrel: wrote ${modules.length} exports`);
  process.exit(0);
}

const actual = await readFile(barrelPath, "utf8");
if (actual !== expected) {
  console.error("src/index.ts is not the generated barrel.");
  console.error("Run: node scripts/check-barrel.mjs --write");
  const actualExports = actual.match(/^export \* from .+$/gm) ?? [];
  const expectedExports = expected.match(/^export \* from .+$/gm) ?? [];
  for (const line of expectedExports.filter((l) => !actualExports.includes(l))) {
    console.error(`  missing: ${line}`);
  }
  for (const line of actualExports.filter((l) => !expectedExports.includes(l))) {
    console.error(`  unexpected: ${line}`);
  }
  if (actualExports.length === expectedExports.length && actualExports.join("\n") !== expectedExports.join("\n")) {
    console.error("  exports are present but not in sorted order");
  }
  process.exit(1);
}
console.log(`barrel: ${modules.length} exports, sorted and complete`);
